# Generated by Django 2.0.7 on 2018-08-04 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0001_create_emotion_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='name',
            field=models.CharField(choices=[('MEL', 'Melancholy'), ('CLM', 'Calm'), ('HPY', 'Happy'), ('EXC', 'Excited')], db_index=True, max_length=3, unique=True),
        ),
    ]
