# Generated by Django 2.0.7 on 2018-08-04 04:21

from django.db import migrations, models
import tunes.models


class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0002_load_initial_emotion_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('artist', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(db_index=True, max_length=36, unique=True)),
                ('valence', models.FloatField(validators=[tunes.models.validate_decimal_value])),
                ('energy', models.FloatField(validators=[tunes.models.validate_decimal_value])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
