# Generated by Django 2.0.7 on 2018-08-04 02:03

from datetime import datetime
import json

from django.db import migrations


def load_emotion_data_from_fixture(apps, schema_editor):
    fixture_file = 'apps/tunes/fixtures/Initial_Emotions.json'
    Emotion = apps.get_model('tunes', 'Emotion')
    db_alias = schema_editor.connection.alias

    with open(fixture_file) as fp:
        emotions = json.load(fp)

    for emotion in emotions:
        params = {
            'pk': emotion['pk'],
            'name': emotion['fields']['name'],
            'lower_bound': emotion['fields']['lower_bound'],
            'upper_bound': emotion['fields']['upper_bound'],
        }

        Emotion.objects.create(**params)


def unload_emotion_data(apps, schema_editor):
    # Intentionally only delete records loaded from initial fixture
    Emotion = apps.get_model('tunes', 'Emotion')
    db_alias = schema_editor.connection.alias
    initial_emotions = [
        'MEL',
        'CLM',
        'HPY',
        'EXC',
    ]

    Emotion.objects.using(db_alias).filter(name__in=initial_emotions).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0002_make_emotion_name_unique'),
    ]

    operations = [
        migrations.RunPython(
            load_emotion_data_from_fixture,
            reverse_code=unload_emotion_data
        )
    ]
