# Generated by Django 2.0.7 on 2018-08-04 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0003_load_initial_emotion_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='lower_bound',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.AlterField(
            model_name='emotion',
            name='upper_bound',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
