# Generated by Django 2.0.7 on 2018-08-04 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0004_update_boundaries_max_digits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='lower_bound',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='emotion',
            name='upper_bound',
            field=models.FloatField(),
        ),
    ]
