# Generated by Django 2.0.7 on 2018-08-04 03:38

from django.db import migrations, models
import tunes.models


class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0005_update_boundaries_to_Float_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='lower_bound',
            field=models.FloatField(validators=[tunes.models.validate_decimal_value]),
        ),
        migrations.AlterField(
            model_name='emotion',
            name='upper_bound',
            field=models.FloatField(validators=[tunes.models.validate_decimal_value]),
        ),
    ]
