# Generated by Django 2.2.16 on 2020-10-03 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0007_remove_db_index_from_emotion_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='code',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
