# Generated by Django 2.2.16 on 2021-01-17 01:26

import base.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0008_remove_db_index_from_song_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='danceability',
            field=base.fields.UnitIntervalField(default=0),
        ),
        migrations.AlterField(
            model_name='emotion',
            name='energy',
            field=base.fields.UnitIntervalField(),
        ),
        migrations.AlterField(
            model_name='emotion',
            name='valence',
            field=base.fields.UnitIntervalField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='danceability',
            field=base.fields.UnitIntervalField(default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='energy',
            field=base.fields.UnitIntervalField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='valence',
            field=base.fields.UnitIntervalField(),
        ),
    ]
