# Generated by Django 2.2.16 on 2021-01-03 00:31

import base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0008_remove_db_index_from_song_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='danceability',
            field=models.FloatField(db_index=True, default=0, validators=[base.validators.validate_decimal_value]),
        ),
        migrations.AlterField(
            model_name='song',
            name='energy',
            field=models.FloatField(db_index=True, validators=[base.validators.validate_decimal_value]),
        ),
        migrations.AlterField(
            model_name='song',
            name='valence',
            field=models.FloatField(db_index=True, validators=[base.validators.validate_decimal_value]),
        ),
    ]
