# Generated by Django 2.0.7 on 2018-08-07 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0003_create_song_table'),
        ('accounts', '0002_create_user_foreign_tables'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useremotion',
            unique_together={('user', 'emotion')},
        ),
    ]
