# Generated by Django 2.1.5 on 2019-01-28 00:43

import base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_prefetch_manager_to_moodyuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremotion',
            name='energy',
            field=models.FloatField(validators=[base.validators.validate_decimal_value]),
        ),
        migrations.AlterField(
            model_name='useremotion',
            name='valence',
            field=models.FloatField(validators=[base.validators.validate_decimal_value]),
        ),
    ]
