# Generated by Django 2.1.5 on 2019-02-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_validators_to_emot_boundaries'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersongvote',
            name='context',
            field=models.CharField(blank=True, choices=[('PARTY', 'Listening to music at a party'), ('RELAX', 'Listening to music to relax'), ('WORK', 'Listening to music while working on a task')], max_length=10),
        ),
        migrations.AddField(
            model_name='usersongvote',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
