# Generated by Django 2.2.10 on 2020-04-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0004_add_song_genre'),
        ('accounts', '0007_create_spotify_user_auth_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersongvote',
            name='context',
            field=models.CharField(blank=True, choices=[('', '-----------'), ('PARTY', 'Listening to music at a party'), ('RELAX', 'Listening to music to relax'), ('WORK', 'Listening to music while working on a task'), ('OTHER', 'Doing something else')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='usersongvote',
            unique_together={('user', 'song', 'emotion', 'context')},
        ),
    ]
