# Generated by Django 2.2.10 on 20200411 02:51

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_uniqueness_constraints_to_usersongvote'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='moodyuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
