# Generated by Django 2.2.10 on 2020-05-01 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_useremotion_danceability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyuserauth',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
