# Generated by Django 2.2.10 on 2020-05-16 04:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_make_spotify_auth_one_to_one_on_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyuserauth',
            name='saved_songs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=36), default=list, size=None),
        ),
    ]
