# Generated by Django 2.2.10 on 2020-05-30 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_make_spotify_auth_one_to_one_on_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremotion',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
