# Generated by Django 2.2.13 on 2020-06-28 03:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_make_spotify_auth_one_to_one_on_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyuserauth',
            name='top_artists',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=None),
        ),
    ]
