# Generated by Django 2.2.13 on 2020-07-03 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_create_spotifyuserdata_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyuserauth',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
