# Generated by Django 2.2.16 on 2021-01-10 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_create_userprofile_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpotifyUserAuth',
        ),
        migrations.DeleteModel(
            name='SpotifyUserData',
        ),
    ]
