# Generated by Django 2.2.13 on 2020-08-01 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_create_userprofile_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_completed_onboarding',
            field=models.BooleanField(default=False),
        ),
    ]
