# Generated by Django 2.2.16 on 2021-01-17 01:26

import base.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_delete_spotifyuserauth_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremotion',
            name='danceability',
            field=base.fields.UnitIntervalField(default=0),
        ),
        migrations.AlterField(
            model_name='useremotion',
            name='energy',
            field=base.fields.UnitIntervalField(),
        ),
        migrations.AlterField(
            model_name='useremotion',
            name='valence',
            field=base.fields.UnitIntervalField(),
        ),
    ]
