repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: no-commit-to-branch
    - id: name-tests-test
      exclude: libs/tests/helpers.py
      name: Check test filename is valid
      args: ['--django']
    - id: debug-statements
    - id: check-merge-conflict
    - id: check-json

- repo: https://github.com/miki725/importanize/
  rev: 'master'
  hooks:
  - id: importanize
    args: [--verbose, --config=.importanize.json]
