language: python

cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit

python:
  - "3.6"

services:
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE mtdj_local;' -U postgres
  - psql -c 'CREATE USER mtdj;' -U postgres
  - psql -c 'ALTER USER mtdj CREATEDB;' -U postgres

install:
  - pip install -r requirements/common.txt
  - pre-commit install

script:
  - pytest
  - flake8
  - pre-commit
  - importanize --config=.importanize.json --ci
