language: python
python:
  - "3.5"

install:
  pip install -r requirements/common.txt

script:
  - echo 'Starting unit tests...'
  - python manage.py test --verbosity=2
  - echo 'Starting linter...'
  - flake8
