name: Lint
on:
  pull_request:
    branches:
      - master
      - production

jobs:
  lint:
    name: Run flake8
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          grep flake8 requirements/common.txt | xargs pip install
      - name: Run flake8
        run: flake8

  pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Get changed files from PR
        uses: futuratrepadeira/changed-files@v3.0.0
        id: changed-files
        with:
          repo-token: ${{ github.token }}
      - name: Set changed files environment variable
        run: |
          echo "::set-env name=FILES::${{ steps.changed-files.outputs.files_created }} ${{ steps.changed-files.outputs.files_updated }}"
      - name: set PY
        run: echo "::set-env name=PY::$(python -VV | sha256sum | cut -d' ' -f1)"
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - uses: pre-commit/action@v1.1.1
        with:
          extra_args: --files ${{ env.FILES }}

  importanize:
    name: Run importanize
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install importanize
        run: |
          python -m pip install --upgrade pip
          grep importanize requirements/common.txt | xargs pip install
      - name: Run importanize
        run: importanize --config=.importanize.json --ci
