name: Lint
on:
  pull_request:
    branches:
      - master
      - production

jobs:
  lint:
    name: Run flake8
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          pip install tox==3.20.0
      - name: Run flake8
        run: tox -e flake8

  pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Get changed files from PR
        uses: futuratrepadeira/changed-files@v3.0.0
        id: changed-files
        with:
          repo-token: ${{ github.token }}
      - name: Set changed files environment variable
        run: |
          echo "FILES=${{ steps.changed-files.outputs.files_created }} ${{ steps.changed-files.outputs.files_updated }}" >> $GITHUB_ENV
      - name: set PY
        run: |
          echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - uses: pre-commit/action@v1.1.1
        with:
          extra_args: --files ${{ env.FILES }}

  requirements-lock-verify:
    name: Verify lock file is in sync with dependency list
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          pip install tox==3.20.0
      - name: Run pip-compile-multi verify
        run: tox -e verify-requirements
