name: Lint
on:
  pull_request:
    branches:
      - master
      - production

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install linter packages
        run: |
          python -m pip install --upgrade pip
          grep flake8 requirements/common.txt | xargs pip install
      - name: Run flake8
        run: flake8
      - name: Get changed files from PR
        uses: futuratrepadeira/changed-files@v3.0.0
        id: changed-files
        with:
          repo-token: ${{ github.token }}
      - name: Set changed files environment variable
        run: |
          echo "::set-env name=FILES::${{ steps.changed-files.outputs.files_created }} ${{ steps.changed-files.outputs.files_updated }}"
      - uses: pre-commit/action@v1.1.0
        with:
          args: --files ${{ env.FILES }}
          token: ${{ secrets.GITHUB_TOKEN }}
