name: Test
on:
  pull_request:
    branches:
      - master
      - production

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Hello World
        run: echo Hello World!
